servlet:
  multipart:
    max-file-size: 10MB # 最大支持文件大小
    max-request-size: 10MB # 最大支持请求大小

#分布式文件系统Fdfsdfs配置
fdfs:
  soTimeout: 1500 #socket连接超时时长
  connectTimeout: 600 #连接tracker服务器超时时长
  thumbImage: #缩略图生成参数，可选
    width: 150
    height: 150
  trackerList: #TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
    - 106.55.157.221:22122
    #    - 192.168.8.102:22122
# 配置SpringMVC文件上传限制，默认1M。注意MB要大写，不然报错。SpringBoot版本不同，配置项不同
  #spring:
    #servlet:
    #multipart:
    #max-file-size: 50MB
  #max-request-size: 50MB
